### ISSUE TITLE
Please add AgentID and Notes to the integration

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-leadperfection#3]
First street online is requesting to deliver to 2 new custom fields in lead perfection. 

Please add AgentID and Notes to the integration. This is per ticket: https://activeprospect.zendesk.com/agent/tickets/6456

Notes direct from LeadPerfection: "AgentID – variable character field. Accepts up to 25 characters 
Notes – variable character field. Set as a MAX since I was not sure if you were putting any limits on the form yourself."

**Comment by kcaponeAP** [comment]
I've got an email into Chris Rivera at LeadPoint to answer if these are standard or custom fields.

**Comment by kcaponeAP** [comment]
These were custom fields added for First Street. They will not be useful to other users of the integration.

**Comment by cgrayson** [comment]
This has been fixed and the new integration deployed. 

Here's how it works. In the mapping to LeadPerfection, map values to the exact name that LeadPerfection expects. No prefix, no `lead.` or `custom.`, no nothin'. 

Like this: 
![screen shot 2015-02-10 at 10 51 03 am](https://cloud.githubusercontent.com/assets/5596/6131595/c0966c24-b112-11e4-8c70-4be20bcad5da.png)

And same for `Notes`, of course. 

This is the way we plan to handle the situation of having to send "custom" fields via a "standard" integration from here on. (But note that the integration has to be coded specifically to do this; it doesn't automatically work this way in all integrations.)
