### ISSUE TITLE
media6 field is repeated in the integration?

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-leadperfection#4]
Please look to the integrations page to see that media6 is repeated as a field:

![screen shot 2015-01-23 at 4 27 15 pm](https://cloud.githubusercontent.com/assets/8238417/5883944/ce3f7da6-a31c-11e4-97da-503274b9be41.png)

**Comment by zalary** [comment]
resolved as of Version 0.1.0
