### ISSUE TITLE
Customize URL

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-leadperfection#8]
See the [background in Zendesk](https://activeprospect.zendesk.com/agent/tickets/7346). 

The LeadPerfection URL is hardcoded to...
`http://#{customerName}.leadperfection.com/batch/LeadFormExtraFields.asp` 

...but we want to be able to configure it as follows in some cases: 
`http://#{customerName}.leadperfection.com/batch/LeadFormTransfer.asp`

**Comment by alexkwolfe** [comment]
I recommend variablizing the last part of the URL in a variable called `action` which could be either "LeadFormTransfer" or "LeadFormExtraFields". 

```
http://#{customerName}.leadperfection.com/batch/#{action}.asp
```

**Comment by alexj** [comment]
The two URLs that the customer will need to point two are:
* http://firststreet.leadperfection.com/batch/LeadFormExtraFields.asp (currently hardcoded into the integration)
* http://firststreet.leadperfection.com/batch/LeadFormTransfer.asp

They believe this is all they will need, so the pattern Alex laid out should be good to go.
